Update Signed Commit Workflow

diff --git a/.github/workflows/reusable-signed-commit.yml b/.github/workflows/reusable-signed-commit.yml
--- a/.github/workflows/reusable-signed-commit.yml
+++ b/.github/workflows/reusable-signed-commit.yml
@@ -26,6 +26,7 @@ jobs:
 
       - name: Set up Git user
         run: |
+          set -e
           chmod +x ./scripts/git-setup.sh
           ./scripts/git-setup.sh
 
@@ -39,55 +40,99 @@ jobs:
             echo "is_pr=false" >> $GITHUB_ENV
           fi
 
-      - name: Generate new branch if not running on a PR
-        if: env.is_pr == 'false'
+      - name: Generate a new branch if not running on a PR
+        if: ${{ env.is_pr == 'false' }}
         run: |
           date=$(date +%Y_%m_%d_%H_%M)
-          branch_name="code_formatter_$date"
+          branch_name="signed_commit_$date"
           git checkout -b $branch_name
           git push -u origin $branch_name
           echo "branch_name=$branch_name" >> $GITHUB_ENV
 
-      - name: Get latest commit SHA
-        id: get_sha
+      - name: Check for changes
         run: |
-          latest_sha=$(git rev-parse HEAD)
-          echo "latest_sha=$latest_sha" >> $GITHUB_ENV
+          set -e
+          git status
+          git diff
+          git add .
+          if git diff --staged --quiet; then
+            echo "No changes detected."
+            exit 0
+          fi
+          echo "Changes detected."
+          echo "changes=true" >> $GITHUB_ENV
+
+      - name: Prepare the Changes for GraphQL
+        if: ${{ env.changes == 'true' }}
+        run: |
+          set -e
+          commit_oid=$(git rev-parse HEAD)
+          echo "commit_oid=$commit_oid" >> $GITHUB_ENV
+
+          files_for_commit='{"additions": []}'
+          while IFS= read -r file; do
+            if [[ -f "$file" ]]; then
+              base64_content=$(base64 -w 0 < "$file")
+              files_for_commit=$(echo "$files_for_commit" | jq --arg path "$file" --arg content "$base64_content" \
+              '.additions += [{ "path": $path, "contents": $content }]')
+            fi
+          done < <(git diff --staged --name-only)
+
+          echo "$files_for_commit" > files_for_commit.json
 
       - name: Create signed commit using GraphQL
+        if: ${{ env.changes == 'true' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh api graphql -f query='
-          mutation($repository: String!, $branchName: String!, $commitMessage: String!, $sha: GitObjectID!) {
-            createCommitOnBranch(input: {
-              branch: {
-                repositoryNameWithOwner: $repository
-                branchName: $branchName
+          set -e
+          commit_message="Automated signed commit update"
+          files_for_commit=$(cat files_for_commit.json)
+
+          mutation_payload=$(jq -n \
+            --arg repository "${{ github.repository }}" \
+            --arg branch_name "$branch_name" \
+            --arg commit_oid "$commit_oid" \
+            --arg commit_message "$commit_message" \
+            --argjson fileChanges "$files_for_commit" \
+            '{
+              query: "mutation($input: CreateCommitOnBranchInput!) { createCommitOnBranch(input: $input) { commit { oid } } }",
+              variables: {
+                input: {
+                  branch: {
+                    repositoryNameWithOwner: $repository,
+                    branchName: $branch_name
+                  },
+                  message: {
+                    headline: $commit_message
+                  },
+                  fileChanges: $fileChanges,
+                  expectedHeadOid: $commit_oid
+                }
               }
-              message: {
-                headline: $commitMessage
-              }
-              expectedHeadOid: $sha
-            }) {
-              commit {
-                oid
-              }
-            }
-          }' \
-          -f repository="${{ github.repository }}" \
-          -f branchName="${{ env.branch_name }}" \
-          -f commitMessage="Automated commit by GitHub Actions" \
-          -f sha="${{ env.latest_sha }}" \
-          -H "Authorization: bearer $GITHUB_TOKEN"
+            }')
+
+          RESPONSE=$(curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" \
+            -H "Content-Type: application/json" \
+            -d "$mutation_payload" https://api.github.com/graphql)
+
+          COMMIT_OID=$(echo "$RESPONSE" | jq -r ".data.createCommitOnBranch.commit.oid")
+
+          if [ "$COMMIT_OID" != "null" ]; then
+            echo "Commit successfully created with OID: $COMMIT_OID"
+          else
+            echo "Error creating commit: $RESPONSE"
+            exit 1
+          fi
 
       - name: Create a PR if not running on a PR
-        if: env.is_pr == 'false'
+        if: ${{ env.is_pr == 'false' && env.changes == 'true' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          set -e
           gh pr create \
             --base main \
-            --head ${{ env.branch_name }} \
+            --head "${{ env.branch_name }}" \
             --title "${{ inputs.pr_title || 'Automated Signed Commit Update' }}" \
             --body "${{ inputs.pr_body || 'This PR was automatically created by a GitHub workflow to apply a signed commit update.' }}"
